# Generated by Django 4.2.1 on 2023-05-06 05:34

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_base_url", models.URLField(unique=True, verbose_name="API Base URL")),
                ("name", models.CharField(max_length=100)),
                ("remote_id", models.CharField(max_length=100)),
                ("secret", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=100)),
                ("access_token", models.CharField(max_length=100)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="client.client")),
            ],
        ),
    ]
